# -*- coding: utf-8 -*-
"""If

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P3gYmg6Cw48YLy5I_5X8A1VCA0WsCSDw

**2. Ler um valor e escrever se é positivo, negativo ou zero.**
"""

Valor = int(input("Valor "))

if Valor > 0:
  print("Positivo")
else:
  if Valor < 0:
    print("Negativo")
  else:
    print("0")

"""**3. Ler um valor e escrever a mensagem É MAIOR QUE 10! se o valor lido for maior que 10,
caso contrário escrever NÃO É MAIOR QUE 10!**
"""

Valor = int(input("Valor "))

if Valor > 10:
  print("Maior que 10")
else:
  if Valor < 10:
    print("Menor que 10")

"""**4. Calcule a soma de dois números, se o resultado for maior que 10, mostre-o na tela.**"""

Valor1 = int(input("Valor 1 "))
Valor2 = int(input("Valor 2 "))
Soma = Valor1 + Valor2

if Soma > 10:
  print(Soma)

"""**5. Entrar com um número e informar se ele é divisível por 5.**"""

Num = int(input("Numero "))
Resto = Num % 5

if Resto == 0:
  print("É divisível")
else:
  print("Não é divisível")

"""**6. Construir um algoritmo que indique se o número digitado está entre 20 e 90 ou não.**"""

Valor = int(input("Valor "))

if Valor >= 20 and Valor <= 90:
  print("Sim")
  print(Valor)
else:
  print(f"Não")

"""**7. Ler o ano atual e o ano de nascimento de uma pessoa. Escrever uma mensagem que
diga se ela poderá ou não votar este ano (não é necessário considerar o mês em que a
pessoa nasceu).**
"""

Ano_nascimento = int(input("Ano de nascimento "))
Ano_atual = int(input("Ano Atual "))
Idade = Ano_atual - Ano_nascimento

if Idade >= 16:
  print(f"Pode votar")
else:
  print(f"Não pode votar")

"""**8. Entrar com o ano de nascimento de uma pessoa e imprimir a idade dela. Verificar se o
ano digitado é válido.**
"""

Ano_nascimento = int(input("Ano de nascimento "))
Ano_atual = int(input("Ano Atual "))
Idade = Ano_atual - Ano_nascimento

if Idade >= 0:
  print(Idade)
else:
  print(f"Valor inválido")

"""**9. Entrar com a idade de uma pessoa e exibir a mensagem; Maior de idade, menor de
idade ou acima de 65 anos.**
"""

Idade = int(input("Idade "))

if Idade >= 65:
  print(f"Idoso")
else:
  if Idade >= 18:
    print(f"Maior de idade")
  else:
    if Idade < 18:
      print(f"Menor de idade")

"""**10. Ler as notas da 1a
. e 2a
. avaliações de um aluno. Calcular a média aritmética simples e
escrever uma mensagem que diga se o aluno foi ou não aprovado (considerar que se a
nota for igual ou maior que 6 o aluno é aprovado). Escrever também a média
calculada.**
"""

Avaliacao1 = int(input("Nota 1 "))
Avaliacao2 = int(input("Nota 2 "))
Media = (Avaliacao1 + Avaliacao2)/2

if Media >= 6:
  print(f"Aprovado")
  print(f"Nota",Media)

"""**11. Escrever um algoritmo para ler duas notas de um aluno e escrever na tela a palavra
“Aprovado” se a média das duas notas for maior ou igual a 7,0. Caso a média seja
inferior a 7,0, o programa deve ler a nota do exame e calcular a média final. Se esta
média for maior ou igual a 5,0, o programa deve escrever “Aprovado”, caso contrário
deve escrever “Reprovado”.**
"""

Avaliacao1 = int(input("Nota 1 "))
Avaliacao2 = int(input("Nota 2 "))
Media = (Avaliacao1 + Avaliacao2)/2

if Media >= 7:
  print(f"Aprovado")
  print(f"Nota",Media)
else:
  Exame = int(input("Nota do exame final "))
  Media_final = (Avaliacao1 + Avaliacao2 + Exame)/3
  if Media_final >= 5:
    print(f"Aprovado")
  else:
    print(f"Reprovado")

"""**12. Escrever um algoritmo para ler a quantidade de horas aula dadas por dois professores
e o valor por hora recebido por cada um. Mostrar na tela qual dos professores tem
salário total maior.**
"""

Horas1 = int(input("Carga horária 1 "))
Valor_h1 = int(input("Valor por hora 1 "))
Salario1 = Horas1*Valor_h1
Horas2 = int(input("Carga horária 2 "))
Valor_h2 = int(input("Valor por hora 2 "))
Salario2 = Horas2*Valor_h2

if Salario1 > Salario2:
  print(f"Professor 1 tem o maior salário")
else:
  print(f"Professor 2 tem o maior salário")

"""**13. Faça um algoritmo que leia um número inteiro e mostre uma mensagem indicando se
este número é par ou ímpar.**
"""

Num = int(input("Numero "))
Resto = Num % 2

if Resto == 0:
  print(f"Par")
else:
  print(f"Impar")

"""**14. Ler o nome de 2 times e o número de gols marcados na partida. Escrever o nome do
vencedor. Caso não haja vencedor deverá ser impressa a palavra EMPATE.**
"""

Time1 = input("Time 1 ")
Gols_t1 = int(input("Gols do Time 1 "))
Time2 = input("Time 2 ")
Gols_t2 = int(input("Gols do time 2 "))

if Gols_t1 > Gols_t2:
  print(Time1,"Venceu")
elif Gols_t2 > Gols_t1:
  print(Time2,"Venceu")
else:
  print("Empate")

"""**15. Entrar com a sigla do estado de uma pessoa e imprimir uma das mensagens: “Carioca,
Paulista, Mineiro ou Outros”**
"""

Sigla = input("Sigla do estado ")

if Sigla == SP:
  print("Paulista")
elif:

"""**16. Um comerciante comprou um produto e quer vendê-lo com um lucro de 45% se o valor
da compra for menor que R$ 20,00; Caso contrário, o lucro será de 30%. Entrar com o
valor do produto e imprimir o valor da venda.**
"""

Valor_prod = float(input("Valor do produto "))

if Valor_prod < 20.00:
  print("Valor de venda", Valor_prod*1.45)
else:
  print("Valor de venda", Valor_prod*1.30)

"""**17. Entrar com um número de 1 a 12 e exibir o mês correspondente.**"""

Mes_num = int(input("Mês em numero "))

if Mes_num == 1:
  print("Janeiro")
elif Mes_num == 2:
  print("Fevereiro")
elif Mes_num == 3:
  print("Março")
elif Mes_num == 4:
  print("Abril")
elif Mes_num == 5:
  print("Maio")
elif Mes_num == 6:
  print("Junho")
elif Mes_num == 7:
  print("Julho")
elif Mes_num == 8:
  print("Agosto")
elif Mes_num == 9:
  print("Setembro")
elif Mes_num == 10:
  print("Outubro")
elif Mes_num == 11:
  print("Novembro")
elif Mes_num == 12:
  print("Dezembro")
else:
  print("Numero invalido")

"""**18. Faça um algoritmo que verifique se uma letra digitada é vogal ou consoante.**"""

Letra = input("Letra ")

if Letra == "a":
  print("Vogal")
else:
  print("Consoante")

"""**19. Ler 2 valores (considere que não serão lidos valores iguais) e escrever o maior deles.**"""

Valor1 = int(input("Valor 1 "))
Valor2 = int(input("Valor 2 "))

if Valor1 > Valor2:
  print(Valor1)
else:
  print(Valor2)

"""**20. Ler 2 valores (considere que não serão lidos valores iguais) e escrevê-los em ordem
crescente.**
"""

Valor1 = int(input("Valor 1 "))
Valor2 = int(input("Valor 2 "))

if Valor1 > Valor2:
  print(Valor2,Valor1)
else:
  print(Valor1,Valor2)

"""**21. Ler 3 valores (considere que não serão informados valores iguais) e escrever o maior
deles.**
"""

Valor1 = int(input("Valor 1 "))
Valor2 = int(input("Valor 2 "))
Valor3 = int(input("Valor 3 "))

if Valor1 > Valor2 and Valor1 > Valor3:
  print(Valor1)
elif Valor2 > Valor3:
  print(Valor2)
else:
  print(Valor3)

"""**22. Ler 3 valores (considere que não serão informados valores iguais) e escrever a soma
dos 2 maiores.**
"""

Valor1 = int(input("Valor 1 "))
Valor2 = int(input("Valor 2 "))
Valor3 = int(input("Valor 3 "))

if Valor1 > Valor2 and Valor3 > Valor2:
  print(Valor1 + Valor3)
elif Valor1 > Valor3 and Valor2 > Valor3:
  print(Valor1 + Valor2)
else:
  print(Valor3 + Valor2)

"""**23. Ler 3 valores (considere que não serão informados valores iguais) e escrevê-los em
ordem crescente.**
"""

Valor1 = int(input("Valor 1 "))
Valor2 = int(input("Valor 2 "))
Valor3 = int(input("Valor 3 "))

if Valor1 > Valor2 and Valor3 > Valor2 and Valor1 > Valor3:
  print(Valor2,Valor3,Valor1)
elif Valor1 > Valor2 and Valor3 > Valor2 and Valor3 > Valor1:
  print(Valor2,Valor1,Valor3)
elif Valor2 > Valor1 and Valor3 > Valor1 and Valor2 > Valor3:
  print(Valor1,Valor3,Valor2)
elif Valor2 > Valor1 and Valor3 > Valor1 and Valor3 > Valor2:
  print(Valor1,Valor2,Valor3)
elif Valor2 > Valor3 and Valor1 > Valor3 and Valor2 > Valor1:
  print(Valor3,Valor1,Valor2)
else:
  print(Valor3,Valor2,Valor1)

Valor1 = int(input("Valor 1 "))
Valor2 = int(input("Valor 2 "))
Valor3 = int(input("Valor 3 "))

if Valor2 > Valor1 and Valor3 > Valor1:
  if Valor3 > Valor2:
    print(Valor1,Valor2,Valor3)
  else:
    print(Valor1,Valor3,Valor2)
if Valor1 > Valor2 and Valor3 > Valor2:
  if Valor1 > Valor3:
    print(Valor2,Valor3,Valor1)
  else:
    print(Valor2,Valor1,Valor3)
if Valor2 > Valor3 and Valor1 > Valor3:
  if Valor2 > Valor1:
    print(Valor3,Valor1,Valor2)
  else:
    print(Valor3,Valor2,Valor1)

"""**24. Faça um algoritmo que leia as duas notas parciais obtidas por um aluno numa
disciplina ao longo de um semestre, e calcule a sua média. A atribuição de conceitos
obedece à tabela abaixo:
Entre 9.0 e 10.0 A
Entre 7.5 e 9.0 B
Entre 6.0 e 7.5 C
Entre 4.0 e 6.0 D
Entre 4.0 e zero E**
"""

Nota1 = float(input("Nota 1 "))
Nota2 = float(input("Nota 2 "))
Media = (Nota1 + Nota2) / 2

if Media >= 9.0:
  print("A / Aprovado")
elif Media >= 7.5 and Media < 9.0:
  print("B / Aprovado")
elif Media >= 6.0 and Media < 7.5:
  print("C / Aprovado")
elif Media >= 4.0 and Media < 6.0:
  print("D / Reprovado")
else:
  print("E / Reprovado")

"""**25. Escrever um algoritmo para ler dois valores e uma das seguintes operações a serem
executadas (codificadas da seguinte forma: 1 – Adição, 2 – Subtração, 3 – Multiplicação
e 4 – Divisão). Calcular e escrever o resultado dessa operação sobre os dois valores
lidos.**
"""

Valor1 = int(input("Valor 1 "))
Valor2 = int(input("Valor 2 "))

"""**26. Faça um algoritmo para calcular as raízes reais de uma equação quadrática: ax2 + bx +
c = 0. Uma equação quadrática só tem raiz reais se (b2 - 4ac) for maior ou igual a
zero. O algoritmo deverá informar as seguintes situações:**

**• Se o delta calculado for negativo, a equação não possui raízes reais. Informe ao
usuário e encerre o programa;**

**• Se o delta calculado for igual a zero a equação possui apenas uma raiz real,
informe-a ao usuário;**

**• Se o delta for positivo, a equação possui duas raiz reais, informe-as ao usuário.**
"""

ax2 = float(input("a "))
bx = float(input("b "))
c = float(input("c "))
Delta = (bx)**2 - 4 * ax2 * c

if Delta > 0:
  print("Delta negativo / equação não possui raiz")
elif Delta == 0:
  print("Delta 0 / equação possui apenas uma raiz real")
else:
  print("Delta positivo / equação possui duas raiz real")

"""**27. Faça um algoritmo que leia 3 valores a, b, c, e verifique se podem ser os
comprimentos dos lados de um triângulo. Em caso afirmativo, verifique se é “triângulo
equilátero”, “triângulo isósceles” ou “triângulo escaleno”. Em caso negativo, escreva
uma mensagem: “os valores lidos não formam um triângulo”. Considere que:**

**• o comprimento de cada lado de um triângulo é menor que a soma dos
comprimentos dos outros lados;**

**• um triângulo equilátero tem três lados iguais;**

**• um triângulo isósceles tem dois lados iguais e um diferente;**

**• um triângulo escaleno tem três lados diferentes.**
"""

Valor1 = int(input("Valor 1 "))
Valor2 = int(input("Valor 2 "))
Valor3 = int(input("Valor 3 "))

if Valor1 < Valor2 + Valor3 and Valor2 < Valor1 + Valor3 and Valor3 < Valor2 + Valor1:
  if Valor1 == Valor2 and Valor2 == Valor3:
    print("Triângulo equilátero")
  elif Valor1 != Valor2 and Valor1 != Valor3 and Valor2 != Valor3:
    print("Triângulo escaleno")
  elif Valor1 == Valor2 or Valor1 == Valor3 or Valor3 == Valor2:
    if Valor1 != Valor2 or Valor1 != Valor3 or Valor3 != Valor2:
      print("Triângulo isósceles")

"""**28. Escreva um algoritmo que leia 4 valores (opção, a, b, c), onde opção é um valor
inteiro e positivo e a, b, c são quaisquer valores reais. Escreva os valores lidos da
seguinte maneira:**

**• se opção = 1 Þ escreva os 3 valores a, b, c em ordem crescente;**

**• se opção = 2 Þ escreva os 3 valores a, b, c em ordem decrescente;**

**• se opção = 3 Þ escreva os 3 valores de forma que o maior valor entre a, b, c fica
entre os outros 2.**


"""

Opcao = input("Opção 1/2/3 ")
Valor1 = int(input("Valor 1 "))
Valor2 = int(input("Valor 2 "))
Valor3 = int(input("Valor 3 "))

if Opcao == "1":
  if Valor2 > Valor1 and Valor3 > Valor1:
    if Valor3 > Valor2:
      print(Valor1,Valor2,Valor3)
    else:
      print(Valor1,Valor3,Valor2)
  if Valor1 > Valor2 and Valor3 > Valor2:
    if Valor1 > Valor3:
      print(Valor2,Valor3,Valor1)
    else:
      print(Valor2,Valor1,Valor3)
  if Valor2 > Valor3 and Valor1 > Valor3:
    if Valor2 > Valor1:
      print(Valor3,Valor1,Valor2)
    else:
      print(Valor3,Valor2,Valor1)
if Opcao == "2":
  if Valor2 < Valor1 and Valor3 < Valor1:
    if Valor3 < Valor2:
      print(Valor1,Valor2,Valor3)
    else:
      print(Valor1,Valor3,Valor2)
  if Valor1 < Valor2 and Valor3 < Valor2:
    if Valor1 < Valor3:
      print(Valor2,Valor3,Valor1)
    else:
      print(Valor2,Valor1,Valor3)
  if Valor2 < Valor3 and Valor1 < Valor3:
    if Valor2 < Valor1:
      print(Valor3,Valor1,Valor2)
    else:
      print(Valor3,Valor2,Valor1)
if Opcao == "3":
  if Valor2 > Valor1 and Valor3 > Valor1:
    if Valor3 > Valor2:
      print(Valor1,Valor3,Valor2)
    else:
      print(Valor1,Valor2,Valor3)
  if Valor1 > Valor2 and Valor3 > Valor2:
    if Valor1 > Valor3:
      print(Valor2,Valor1,Valor3)
    else:
      print(Valor2,Valor3,Valor1)
  if Valor2 > Valor3 and Valor1 > Valor3:
    if Valor2 > Valor1:
      print(Valor3,Valor2,Valor1)
    else:
      print(Valor3,Valor1,Valor2)

"""**29. Uma empresa decidiu conceder um aumento de salário a seus funcionários de acordo
com a tabela:**

**em R$ / Índice de Aumento**

**salário <= 400.00 / 15%**

**400.00 < salário <= 700.00 / 12%**

**700.00 < salário <= 1000.00 / 10%**

**1000.00 < salário <= 1500.00 / 7%**

**1500.00 < salário <= 2000.00 / 4%**

**salário > 2000.00 / sem aumento**

**Faça um algoritmo que leia o salário atual de um funcionário e escreva o índice de
aumento e o valor do salário corrigido.**
"""

Salario = float(input("Salário "))

if Salario <= 400.00:
  print(Salario*1.15)
elif 400.00 < Salario <= 700.00:
  print(Salario*1.12)
elif 700.00 < Salario <= 1000.00:
  print(Salario*1.10)
elif 1000.00 < Salario <= 1500.00:
  print(Salario*1.07)
elif 1500.00 < Salario <= 2000.00:
  print(Salario*1.04)
elif Salario > 2000.00:
  print(Salario)

"""**30. Faça um algoritmo para calcular o reajuste salarial de um funcionário, de acordo com
os critérios abaixo:**

**• se salário é inferior a R 10.000,00 deve ter um reajuste de 55%;**

**• se salário está entre R 10.000,00 (inclusive) e R 25.000,00 (inclusive) deve ter
um reajuste de 20%;**

**• se salário é superior a R 25.000,00 deve ter um reajuste de 20%.**
"""

Salario = float(input("Salário "))

if Salario < 10000.00:
  print(Salario*1.55)
elif 10000.00 <= Salario <= 25000.00:
  print(Salario*1.20)
elif 25000.00 < Salario:
  print(Salario*1.20)