# -*- coding: utf-8 -*-
"""Introdução a Python (Lista 1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_Lh2i7qyNgdRiQUOF7aWTkM-7WpfpB6
"""

n1 = int(input("Numero 1 = "))
n2 = int(input("Numero 2 = "))

print("Soma =" ,n1 + n2)

n1 = int(input("Valor em metros "))

print("Milimetros =" ,n1 * 1000)

d = int(input("Dias "))
h = int(input("Horas "))
m = int(input("Minutos "))
s = int(input("Segundos "))

print("Total de segundos=" ,d*86400 + h*3600 + m*60 + s)

s = int(input("Salário "))
a = int(input("Aumento em porcentagem "))

print("Valor do aumento = R$" ,s * (a / 100))
print("Novo salário = R$" , s + s * (a / 100))

p = int(input("Preço do produto "))
d = int(input("Desconto em porcentagem "))

print("Desconto = R$" ,p * (d / 100))
print("Preço a pagar = R$" ,p - p * (d / 100))

d = int(input("Distância a percorrer em Km "))
v = int(input("Velôcidade média "))

print("Tempo para chegar =" ,d / v)

c = float(input("Celsius "))

print("Fahrenheit =" , 9 * c / 5 + 32)

f = float(input("Fahrenheit "))

print("Celsius =" , (f - 32) * 5/9)

d = float(input("Distancia percorrida em Km "))
di = float(input("Dias alugados "))

print("Quantia a pagar = R$" , di * 60 + d * 0.15)

q = int(input("Quantidade de cigarros por dias "))
a = int(input("Anos fumados "))

print("Tempo perdido em dias =" ,((q * (360 * a)) * 10) // 1440)

import sys
sys.set_int_max_str_digits(0)

print(len(str(2**1000000)))