# -*- coding: utf-8 -*-
"""While

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJ1ovEMWqg6bYl711Jr028TgrBzNNjm5

**1. Faça um algoritmo que:**

**• leia 5 números inteiros;**

**• escreva os números que são negativos;**

**• escreva a média dos números positivos.**
"""

conta = 0
somapos = 0
contapos = 0

while conta < 5:
  num = int(input("Digite o número "))
  if num < 0:
    print(num, "Negativo")
    conta = conta + 1
  else:
    somapos = somapos + num
    print("Média dos positivos", somapos/conta)
    conta = conta + 1

somapos = 0
media = 0

for i in range(5):
  num = int(input("Digite o número "))
  if num < 0:
    print(num, "Negativo")
  else:
    somapos = somapos + num
    media = media + 1
    print("Média dos positivos", somapos/media)

"""**2. Faça um algoritmo que leia 5 números inteiros e escreva, para cada número lido, se é
par ou ímpar.**
"""

for i in range(5):
  num = int(input("Digite o número "))
  if (num%2) == 0:
    print(num, "É Par")
  else:
    print(num, "É Ímpar")

"""**3. Dado um conjunto de valores inteiros positivos, determinar qual o menor e qual o
maior valor do conjunto. Um número com valor “0” (zero) indica o fim dos dados e
não deve ser considerado.**
"""

num = 1
menor = -9999
maior = 9999

while num != 0:
  num = int(input("Digite o número "))
  if num < maior:
    maior = num
  elif num > menor:
    menor = num

print("O maior número do conjunto é", maior)
print("O menor número do conjunto é", menor)

"""**4. Faça um algoritmo que calcule e escreva a soma dos números pares e a soma dos
números ímpares entre 1 e 100.**
"""

conta = 1
par = 0
imp = 0

while conta < 10:
  conta = conta + 1
  if (conta%2) == 0:
    par = par + conta
  else:
    imp = imp + conta

print("Soma dos pares", par, "Soma dos ímpares", imp)

"""**5. Faça um algoritmo que leia a altura de 20 pessoas e calcule a média aritmética das
alturas.**
"""

alturas = 0
media = 0

for i in range(5):
  altura = int(input("Digite a altura "))
  alturas = alturas + altura
  media = media + 1

print("Média das alturas", alturas/media)

"""**6. Faça um algoritmo que leia n valores inteiros e escreva quantos desses valores são
negativos.**
"""

neg = 0

for i in range (5):
  valor = int(input("Digite o valor "))
  if valor < 0:
    neg = neg + 1

print(neg, "São negativo")

"""**7. Faça um algoritmo que leia a quantidade de tinta que uma caneta, e enquanto a
caneta tiver tinta para escrever, escreva “Enquanto tem tinta a caneta escreve...”.
Considere que a cada comando de escrita a caneta gasta 2% da tinta que possui.**
"""

qtinta = int(input("Quantidade de tinta "))

while qtinta > 20:
  print("Enquanto tem tinta a caneta escreve...")
  qtinta = qtinta - (qtinta * 0.02)

"""**8. Faça um algoritmo que leia n pares de valores, sendo o primeiro valor o número de
inscrição do atleta e o segundo a altura (em cm) do atleta. Escreva:**

**• o número de inscrição e a altura do atleta mais alto;**

**• o número de inscrição e a altura do atleta mais baixo;**

**• a altura média do grupo de atletas.**
"""

menor = -9999
maior = 9999
nmenor = 0
nmaior = 0
media = 0
alturas = 0

for i in range (5):
   altura = int(input("Digite o número "))
   num = int(input("Número de incrição "))
   media = media + 1
   alturas = alturas + altura
   if altura < maior:
    maior = altura
    nmaior = num
   elif altura > menor:
    menor = altura
    nmenor = num

print("O maior atleta do grupo é o numero", nmaior, "com", maior)
print("O menor atleta do grupo é o numero", nmenor, "com", menor)
print("A média de altura é", alturas/media)

"""**9. Faça um algoritmo que calcule e imprima os valores de y, onde:
y= (3 + 2x + 6x^2) / (1 + 9x + 16x^2), para x variando de 1.0 até 5.0, em intervalos de 0.1 unidades.**
"""

x = 1

while x < 1.5:
  y = (3 + 2 * x + 6 * x**2) / (1 + 9 * x + 16 * x**2)
  print("y é igual a", y)
  x = x + 0.1

"""**10. Construir um algoritmo que calcule o fatorial de um número N.**"""

num = int(input("Número "))

for i in range(1,num):
  num = num * i

print(num)

num = int(input("Número "))
fat = 1
i = 1

while num >= i:
  fat = fat * i
  i = i + 1

print(fat)

"""**11. Faça um algoritmo que calcule e escreva a soma da seguinte série de 100 termos: 1+ 2 + 3 + 4 +!+100**"""

soma = 0

for i in range(1,10):
  soma = soma + i

print(soma)

"""**12. Faça um algoritmo que calcule e escreva a soma da seguinte série de 100 termos: 1/1 + 1/2 + 1/3 + ... 1/100**"""

soma = 0

for i in range(1,10):
  soma = soma + (1/i)

print(soma)

"""**13. Fazer um algoritmo para calcular o valor de S, dado por: S = 1/N + 2/N-1 + 3/N-2 + ... N-1/2 + N/1 ,sendo N lido.**"""

N = int(input("N "))
S = 0

for i in range(1,N+1):
  S = S + i/(N-(i-1))

print(S)

"""**14. O valor aproximado do número pi pode ser calculado usando-se a série:**

**S = 1-(1/3^3)+(1/5^3)-(1/7^3)+(1/9^3)**

**sendo o valor de pi = ^3/S*32 Faça um algoritmo que calcule e escreva o valor de p
usando os 51 primeiros termos da série.**
"""

import math
import numpy as np

neg = 0
pos = 0

for i in range(51):
  neg = neg - (1/(3+4*i)**3)
  pos = pos + (1/(5+4*i)**3)

S = 1 + neg - pos
pi = np.cbrt(S*32)

print(S)
print(pi)

"""**15. Fazer um algoritmo que calcule e escreva a soma dos 20 primeiros termos da série:**

**100/0! + 99/1! + 98/2!**
"""

soma = 100
fat = 1

for i in range(1,6):
  fat = fat * i
  soma = soma + ((100-i)/fat)

print(soma)

"""**16. Fazer um algoritmo que calcule e imprima o valor de ex através da série:**

**e^x = x^0 + x^1/1! + x^2/2!**

**Considerar para efeitos de cálculo os 30 primeiros termos. O algoritmo deverá ler o
valor de x.**
"""

x = int(input("x "))
ex = 1
fat = 1

for i in range(1,6):
  fat = fat * i
  ex = ex + ((x**i)/fat)

print(f" {ex:,.30f} ")

"""**17. Foi feita uma pesquisa de audiência de canal de TV em n casas de um determinado
bairro de Joinville, em um certo dia do mês. Na pesquisa foi utilizado um coletor de
dados portátil. Para cada casa visitada, foi fornecido o número do canal (4, 5, 9, 12) e
o número de pessoas que estavam assistindo a TV naquele horário, considerando que
em cada casa só existia uma televisão. Em casas onde a televisão estava desligada, foi
registrado zero para o número do canal e para o número de pessoas. Faça um
algoritmo que calcule e escreva, para cada emissora, o percentual de audiência.**
"""

import random

casas = int(input("Número de casas "))
canais = [0,4,5,9,12]
aud0 = 0
aud4 = 0
aud5 = 0
aud9 = 0
aud12 = 0

for i in range(casas):
  canal = random.choice(canais)
  print(canal)
  if canal == 0:
    aud0 = aud0 + 1
  elif canal == 4:
    aud4 = aud4 + 1
  elif canal == 5:
    aud5 = aud5 + 1
  elif canal == 9:
    aud9 = aud9 + 1
  else:
    aud12 = aud12 + 1

print(f"Audiência nula {(aud0/casas)*100}%")
print(f"Audiência canal 4 {(aud4/casas)*100}%")
print(f"Audiência canal 5 {(aud5/casas)*100}%")
print(f"Audiência canal 9 {(aud9/casas)*100}%")
print(f"Audiência canal 12 {(aud12/casas)*100}%")

"""**18. Uma companhia de teatro planeja dar uma série de espetáculos. A direção calcula que,
a RS 5,00 o ingresso, serão vendidos 120 ingressos. Com a diminuição de RS 0,50 no
preço dos ingressos, espera-se que haja um aumento de 26 ingressos vendidos. As
despesas estão estipuladas em R$ 200,00 independente do número de ingressos
vendidos. Faça um algoritmo que escreva uma tabela contendo o preço do ingresso, o
número de ingressos e o lucro esperado em função do preço do ingresso, fazendo-se
variar este preço de RS 5,00 a RS 1,00 de RS 0,50 em RS 0,50. Escreva também o lucro
máximo esperado, o preço e o número de ingressos correspondentes.**
"""

preco = 5.00
ingre = 120.00
despe = -200.00

while preco >= 1.00:
  print(f"Preço do ingresso {preco:,.2f}")
  print(f"Quantia de ingressos {ingre:,.2f}")
  print(f"Lucro {despe+(ingre*preco):,.2f}")
  ingre = ingre + (ingre*0.22)
  preco = preco - 0.50

"""**19. Faça um algoritmo que leia n números inteiros e escreva, para cada número lido, os
divisores e quantidade de divisores.**

**EXEMPLO: número lido = 12**

**divisores = 1, 2, 3, 4, 6, 12**

**quantidade divisores = 6**
"""

n = int(input("Número = "))
div = 1
quant = 1

for i in range(2,50):
  resto = n % i
  if resto == 0:
    div = (f"{div}, ") + str(i)
    quant = quant + 1

print(f"Divisores = {div}")
print(f"Quantia de divisores = {quant}")

"""**20. Uma máquina de biscoito está com problemas. Quando ligada, após 1 hora ela quebra
1 biscoito, na segunda hora ela quebra 3 biscoitos, na hora seguinte ela quebra 3
vezes a quantidade de biscoitos quebrados na hora anterior, e assim por diante. Faça
um algoritmo que calcule quantos biscoitos são quebrados no final de cada dia (a
máquina opera 16 horas por dia).**
"""

bisq = 1
hdias = int(input("Dias ")) * 16

for i in range(hdias):
  bisq = bisq * 3

print(f"Biscoistos quebrados {bisq}")

"""**21. Uma turma tem 50 alunos. Faça um algoritmo que:**

**• leia para cada aluno o seu nome e idade;**

**• escreva os nomes dos alunos que tem 18 anos;**

**• escreva a quantidade de alunos que tem idade acima de 20 anos.**
"""

m20 = 0
m18 = ""

for i in range(2):
  nome = input("Nome do aluno ")
  idade = int(input("Idade "))
  if idade == 18:
    m18 = (f"{m18}") + nome + ", "
  elif idade >= 20:
    m20 = m20 + 1

print(f"Maiores de 18 = {m18}...")
print(f"Maiores de 20 = {m20}")

"""**22. Faça um algoritmo que:**

**• leia, para n pessoas, a altura e o sexo (sexo = 'M' ou sexo = 'm' para masculino e
sexo = 'F' ou sexo = 'f' para feminino);**

**• escreva a média da altura das mulheres;**

**• escreva a média da altura da turma.**
"""

npesso = int(input("Número de pessoas "))
somaM = 0
somaF = 0
mediaM = 0
mediaF = 0

for i in range(npesso):
  sexo = input("Sexo ")
  altu = float(input("Altura "))
  if sexo == "M" or sexo == "m":
    somaM = somaM + altu
    mediaM = mediaM + 1
  elif sexo == "F" or sexo == "f":
    somaF = somaF + altu
    mediaF = mediaF + 1

if mediaM > 0:
  print(f"Média de altura M {somaM/mediaM}")
elif mediaF > 0:
  print(f"Média de altura F {somaF/mediaF}")

"""**23. Uma loja de departamentos oferece para seus clientes um determinado desconto de
acordo com o valor da compra efetuada. O desconto é de 20% caso o valor da compra
seja maior que R$ 500,00 e de 15% caso seja menor ou igual. Faça um algoritmo que
leia, para cada cliente, nome, endereço e valor da compra e escreva o total a pagar.
Um nome de cliente igual a ULTIMO indica o fim da entrada de dados.**
"""

cliente = ""

while cliente != "ULTIMO":
  cliente = input("Nome do cliente ")
  if cliente != "ULTIMO":
    ende = input("Endereço ")
    valorc = float(input("Valor da compra "))
    print(cliente)
    print(ende)
    if valorc > 500:
      desc = valorc - (valorc*0.20)
      print(desc)
    else:
      desc = valorc - (valorc*0.15)
      print(desc)

"""**24. Faça um algoritmo que leia valores, sendo que cada valor representa a idade de uma
pessoa. Calcule e escreva a idade média do grupo de pessoas. Só devem ser
computados no cálculo valores maiores do que zero. O algoritmo deve apresentar ao
usuário a seguinte mensagem:**

**deseja digitar mais um valor: s (SIM) / n (NAO)?, antes de prosseguir com a entrada de dados.**
"""

idades = 0
media = 0
opcao = "s"

while opcao != "n" and opcao == "s":
  idade = int(input("Idade da pessoa "))
  if idade > 0:
    idades = idades + idade
    media = media + 1
  opcao = input("deseja digitar mais valores: s/n ")

print(f"Média de idade = {idades/media}")

"""**25. Um hotel cobra R$ 50,00 de diária por hóspede e mais uma taxa de serviços. A taxa de
serviços é de:**

**• R$ 7,50 por diária, caso o número de diárias seja menor que 15;**

**• R$ 6,50 por diária, caso o número de diárias seja igual a 15;**

**• R$ 5,00 por diária, caso o número de diárias seja maior que 15.**

**Faça um algoritmo que apresente as seguintes opções ao recepcionista:**

**1. encerrar a conta de um hóspede**

**2. verificar número de contas encerradas**

**3. finalizar a execução**
"""

cont = "s"
conta = 0

while cont != "n" and cont == "s":
  hospe = input("Hospede ")
  dia = int(input("Número de diarias "))
  conta = conta + 1
  if dia < 15:
      print(f"{(50*dia)+(7.50*dia)}")
  elif dia == 15:
      print(f"{(50*dia)+(6.50*dia)}")
  elif dia > 15:
      print(f"{(50*dia)+(5.00*dia)}")
  cont = input("Continuar? ")

print(f"Foram encerradas {conta} contas")

"""**26. Um determinado material radioativo perde metade de sua massa a cada 50 segundos.
Dada a sua massa inicial em Kg, faça um algoritmo que determine o tempo necessário
para que essa massa se torne menor que 0,5 gramas. Escreva a massa inicial, a massa
final e o tempo.**
"""

imass = int(input("Massa inicial em Kg "))
fmass = 1000 * imass
tempo = 0

while fmass > 0.5:
  fmass = fmass / 2
  tempo = tempo + 50

print(f"Massa inicial = {imass} g")
print(f"Massa final = {fmass} g")
print(f"Tempo necessário = {tempo} segs.")

"""**27. Um motorista acaba de voltar de um feriado prolongado. Antes de sair de viagem e
imediatamente após retornar, o motorista encheu o tanque do veículo e registrou as
medidas do odômetro. Em cada parada feita durante a viagem, foi registrado o valor
do odômetro e a quantidade de combustível comprado para reabastecer o veículo
(suponha que o tanque ficou vazio e foi enchido a cada parada). Faça um algoritmo
que leia o número total de reabastecimentos feitos (incluindo o primeiro) e os dados
registrados relativos à compra de combustível. Calcule e escreva:**

**a) a quilometragem obtida por litro de combustível entre cada par de paradas;**

**b) a quilometragem média obtida por litro de combustível em toda a viagem.**
"""

abast = 1
cont = "s"
odovm = 0
odov = int(input("Valor do odômetro "))
qcom = int(input("Quantidade de combustível "))
odovm = odovm + (odov/qcom)

while cont == "s" and cont != "n":
  odov = int(input("Valor do odômetro "))
  qcom = int(input("Quantidade de combustível "))
  abast = abast + 1
  odovm = odovm + (odov/qcom)
  print(f"Foram {odov/qcom} KM por litro")
  cont = input("Continuar? s/n ")

print(f"A quilometragem média obtida foi {odovm/abast}")

"""**28. Em uma disputa de pingue-pongue os pontos são anotados como D, ponto para o
jogador do lado direito, e E, ponto para o jogador do lado esquerdo da mesa. Faça um
algoritmo que leia o código do ponto de cada jogada e determine o vencedor. A
partida encerra quando:**

**a) um dos jogadores chegar a 21 pontos e a diferença de pontos entre os jogadores for
maior ou igual a dois;**

**b) o jogador com mais de 21 pontos conseguir uma diferença de dois pontos sobre o
adversário, caso a primeira condição não seja atendida.**
"""

pontos = 0
D = 0
E = 0

while D < 5 and E < 5 or pontos < 2:
  D = int(input("Pontos da direita "))
  E = int(input("Pontos da esquerda "))
  pontos = abs(D-E)

"""**29. Os regulamentos de uma competição de pesca impõem um limite no peso total de
pesca de um dia. Faça um algoritmo que leia o limite diário (em quilogramas) e então
leia o peso (em gramas) de cada peixe e escreva o peso total da pesca obtido até
aquele ponto. Quando o limite diário for excedido escreva uma mensagem e encerre a
execução do algoritmo. O algoritmo deve ainda apresentar ao usuário a seguinte
mensagem: informar o peso de mais um peixe: s (SIM) / n (NÃO)? antes de prosseguir
com a entrada de dados.**
"""

limd = int(input("Limite diário / Kg "))
tpesso = 0
cont = "s"

while tpesso < limd and cont == "s":
  peixe = int(input("Pesso do peixe / g "))
  tpesso = tpesso + (peixe/1000)
  print(f"Pesso total da pesca {tpesso} Kg")
  cont = input("Continuar? s/n ")

print("Limite diário excedido")

"""**30. Foi feita uma pesquisa do consumo mensal de energia elétrica em uma determinada
cidade. Para cada consumidor, são fornecidos os seguintes dados: número de
identificação do consumidor, quantidade de kWh consumidos durante o mês, código
do tipo de consumidor (R - residencial, C - comercial, I - industrial). Faça um algoritmo
que:**

**a) leia o preço do kWh por tipo de consumidor;**

**b) leia os dados de n consumidores;**

**c) escreva o número de identificação e o total a pagar, para cada consumidor;**

**d) escreva a quantidade total de KWh consumida para cada um dos três tipos de
consumidores;**

**e) escreva a quantidade média geral de consumo.**
"""

nconsu = int(input("Número de consumidores "))
Rpreço = int(input("Preço Residencial "))
Cpreço = int(input("Preço Comercial "))
Ipreço = int(input("Preço Industrial "))
Rtotal = 0
Ctotal = 0
Itotal = 0


for i in range(nconsu):
  numid = input("Número de identificação ")
  quant = int(input("Quantidade consumida "))
  tipo = input("Tipo do do consumidor R/C/I ")
  if tipo == R:
    Rtotal = Rtotal + quant
    Rconta = quant * Rpreço
    print(f"Consumidor {numid} / Total a pagar = {Rconta}")
  elif tipo == C:
    Ctotal = Ctotal + quant
    Cconta = quant * Cpreço
    print(f"Consumidor {numid} / Total a pagar = {Cconta}")
  elif tipo == I:
    Itotal = Itotal + quant
    Iconta = quant * Ipreço
    print(f"Consumidor {numid} / Total a pagar = {Iconta}")
  media = media + 1

print(f"Total a pagar Residencial {Rtotal}")
print(f"Total a pagar Comercial {Ctotal}")
print(f"Total a pagar Industrial {Itotal}")
print(f"Média de consumo geral {(Rtotal+Ctotal+Itotal)/media}")