# -*- coding: utf-8 -*-
"""Bibliotecas, Pacotes e Módulos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f82ONYz1L-YsuPJwXhQY8ElhOPOylf7i

**1. Importe o módulo math e calcule a raiz quadrada de um número inteiro.**
"""

from math import sqrt

sqrt(4)

"""**2. Importe o módulo datetime e exiba a data e hora atuais.**"""

import datetime

print(datetime.datetime.now())

"""**3. Use o módulo string para verificar se uma string contém apenas dígitos.**"""

oi = "1"
tchau = "a"

print(oi.isdigit())
print(tchau.isdigit())

"""**4. Importe o módulo random e gere um número aleatório entre 1 e 100.**"""

from random import randint

print(randint(1,100))

"""**5. Importe a biblioteca numpy e crie uma array com os números de 1 a 10.**"""

import numpy

print(numpy.arange(1,11))

"""**6. Escreva um programa que importe o pacote numpy e crie uma matriz de zeros
com dimensões 3x3.**
"""

import numpy

numpy.zeros((3,3))

"""**7. Importe a biblioteca matplotlib e crie um gráfico de barras simples com alguns
dados fictícios.**
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array(["A", "B", "C"])
y = np.array([1,2,3])

plt.bar(x,y)

"""**8. Escreva um programa que importe o pacote matplotlib e plote a função seno.**"""

import matplotlib.pyplot as plt
import numpy as np

Fs = 8000
f = 5
sam = 8000

x = np.arange(sam)
y = np.sin(2 * np.pi * f * x / Fs)

plt.plot(x, y)
plt.show()

"""**Importe o pacote requests e faça uma requisição HTTP para um URL e exiba o
código de status.**
"""

import requests

url = 'https://www.example.com'
r = requests.get(url)

print(r)

"""**Importe a biblioteca pandas, leia um arquivo CSV (por exemplo, "dados.csv") e
exiba as primeiras linhas do DataFrame.**
"""

import pandas

data = pandas.read_csv("dataset.csv")

data.head(1)

"""**Escreva um programa que importe o módulo os e imprima o diretório de trabalho
atual.**
"""

import os

os.getcwd()

"""**Escreva um programa que importe o pacote beautifulsoup4 e faça a raspagem
de dados (web crawling) de uma página HTML.**
"""

from bs4 import BeautifulSoup
import requests

url = 'https://www.example.com'
r = requests.get(url)

soup = BeautifulSoup(r.text, "html.parser")
print(soup)

"""**Crie um módulo personalizado chamado de calculadora com uma função que
some dois números. Em seguida, importe e use essa função.**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile calc.py
# 
# def Calculadora(x, y):
#   r = x+y
#   return r

import calc

print(calc.Calculadora(3, 2))

"""**Suponha que estamos desenvolvendo um jogo. Uma possível organização de
pacotes e módulos poderia ser mostrada na figura abaixo.**

**Nota: Um diretório deve conter um arquivo chamado __init__.py para que o
Python o considere um pacote. Este arquivo pode ser deixado vazio, mas
geralmente colocamos o código de inicialização desse pacote neste arquivo.**

**Baseado na figura acima, execute os comandos necessários que se seguem.**

**a) Importar o módulo start**

**b) Suponha que este módulo (i.e. start), contém uma função chamada
select_dificulty(). Qual o comando para importá-lo?**

**c) Importe o módulo change sem usar o prefixo do pacote**

**d) Agora escreva o comando para importar o módulo play**
"""

import game.Level.start

import game.Level.start.select_dificulty()

import game.Image.change

import game.Sound.play