# -*- coding: utf-8 -*-
"""Dicionario

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A1Hme0Wu6UJ6VrugwGMn8lNla6NBbDcO

**1. Crie um dicionário que contenha os nomes de 10 pessoas e suas respectivas
idades.**

**2. Imprima o nome e a idade de todas as pessoas no dicionário.**

**3. Crie uma função que receba um nome como parâmetro e retorne a idade da
pessoa correspondente no dicionário.**

**4. Crie uma função que receba um nome e uma nova idade como parâmetros e
atualize a idade da pessoa correspondente no dicionário.**

**5. Crie uma função que remova uma pessoa do dicionário.**

**6. Crie uma função que retorne a quantidade de pessoas no dicionário.**

**7. Crie uma função que retorne a média das idades das pessoas no dicionário.**

**8. Crie uma função que retorne a pessoa mais velha do dicionário.**

**9. Crie uma função que retorne a pessoa mais nova do dicionário.**

**10. Crie uma função que retorne uma lista com as pessoas cujo nome começa com a
letra "J".**
"""

import random

#

person_age = {'Alice':0, 'Bob':0, 'Carol':0, 'Bisnaga':0}

#

for person, age in person_age.items():
  person_age[person] = random.randint(1,90)

for person, age in person_age.items():
  print(f'{person} | Idade: {age}')

print('')
#

def Function(MainTarget):
  print('')

  if MainTarget == 'Busca':
    name = input('Nome ')
    print("")
    print(f"{name} Tem {person_age[name]} anos")
    print("")

  if MainTarget == 'Remover':
    person_age.pop(input("Nome "))
    print("")

  if MainTarget == 'Modificar':
    name = input('Nome ')
    person_age[name] = int(input('Idade '))
    print("")
    for person, age in person_age.items():
      print(f'{person} | Idade: {age}')

  if MainTarget == 'Quantia':
    print(f'{len(person_age)}')

  if MainTarget == 'Media':
    print(f'{(sum(person_age.values()) / (len(person_age))):.2f}')

  if MainTarget == 'Velho':
    idadeV = 0
    for person, age in person_age.items():
      if  idadeV < age:
        older = person
        idadeV = age
    print(f'{older} É o mais velho(a): {idadeV}')

  if MainTarget == 'Novo':
    idadeN = 999
    for person, age in person_age.items():
      if  idadeN > age:
        younger = person
        idadeN = age
    print(f'{younger} É o mais novo(a): {idadeN}')

  if MainTarget == 'Filtro':
    result = []
    letra = input("Coloque a primeira letra ")
    letra = letra.upper()
    for person in person_age.keys():
      if person[0] == letra:
        result.append(person)
    print(result)

#

print(f'Funções | 1 = Busca | 2 = Remover | 3 = Modificar | 4 = Quantia | 5 = Media | 6 = Mais velho | 7 = Mais novo | 8 = Filtro')
print('')

funcoes = {1:'Busca', 2:'Remover', 3:'Modificar', 4:'Quantia', 5:'Media', 6:'Velho', 7:'Novo', 8:'Filtro'}
chave = int(input("Função "))
print('')

chave = funcoes[chave]

Botao = Function(chave)