# -*- coding: utf-8 -*-
"""Lista de Revisão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reuow-N6OKgMYbbK73A952a04oZyhS8f

**Crie um jogo que embaralhe uma palavra e a mostre ao jogador. O objetivo dele é
acertar a palavra em no máximo 5 tentativas. Informe sempre quantas tentativas ele
ainda tem. Se ele acertar, dê os parabéns; se errar dê uma palavra de ânimo (de
preferência não fixa). Ao final, mostre a palavra correta e o número de tentativas que
ele utilizou.**

**Incluir escolha de temas para as palavras (cidades, cores, times, países, objetos, etc.)
e níveis de dificuldade (ex: iniciante, intermediário, avançado).**
"""

from random import shuffle

# Dificuldade


print(f"Iniciante = 1 / Intermediário = 2 / Avançado = 3")
print("")

dificuldade = int(input("Dificuldade "))

print(f"Cores = 1 / Paises = 2")
print("")

tema = int(input("Tema "))

if dificuldade == 1:
  if tema == 1:
    cores1 = ['ROSA', 'AZUL', 'ROXO','VERDE','VERMELHO' ]
    escolha = cores1
  if tema == 2:
    paises1 = ['JAPÃO', 'BRASIL', 'RUSSIA']
    escolha = paises1

elif dificuldade == 2:
  if tema == 1:
    cores2 = ['CIANO', 'MARROM', 'MUSGO']
    escolha = cores2
  if tema == 2:
    paises2 = ['MÉXICO', 'IRLANDA', 'GRÉCIA']
    escolha = paises2

else:
  if tema == 1:
    cores3 = ['ZAFFRE', 'XANADU', 'VIOLETAESCURO']
    escolha = cores3
  if tema == 2:
    paises3 = ['CHILE', 'POLÔNIA', 'HUNGRIA']
    escolha = paises3


#

def Tentativas(Lista):
  max_tent = 0
  tent = ''
  shuffle(Lista)

  print("")
  print(f"Número de letras = {len(Lista[0])}")
  print("")

  while tent != Lista[0] and max_tent != 5:

    l_certo = []
    l_scerto = []
    rem = []
    tent = input(f"Tentativa [{max_tent}] ")
    print("")
    tent = tent.upper()
    tent = tent.replace(" ", "")
    tent_list = list(tent)
    p_list = list(Lista[0])

    for i in range(len(tent_list)):
      cont = 0
      for j in range(len(p_list)):
        if tent_list[i] == p_list[j]:
          if i == j:
            l_certo.append(f'{tent_list[i]} [{i}]')
          elif i != j and cont < 1:
            l_scerto.append(f'{tent_list[i]} [{i}]')
            cont = cont + 1

    for i in range(len(l_certo)):
      for j in range(len(l_scerto)):
        if l_certo[i] == l_scerto[j]:
          rem. append(l_scerto[j])

    for i in range(len(rem)):
      remov = rem[i]
      l_scerto.remove(remov)

    print(f'{tent_list}')
    print(f'Letras acertadas {l_certo}')
    print(f'Certadas em posição errada {l_scerto}')
    print('')

    max_tent = max_tent + 1

  if max_tent >= 5:
    Resultado = "Falha"
  else:
    Resultado = "Sucesso"
  return Resultado, max_tent, Lista[0]



result = Tentativas(escolha)

#

print(f'{result[0]}')
print(f'Número de tentátivas = {result[1]}')
print(f'{result[2]}')