# -*- coding: utf-8 -*-
"""Atividade Prática 06 Herança

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TOrAJTIBSgtWtXj4h0U3lh4-9mdF9BBz
"""

class Usuario():
  def __init__(self,Nome):
    self._nomeUsuario = Nome

class Admin(Usuario):
  def escrevaNome(self):
    return "admin"
  def digaOla(self):
    return f"Olá Admin, {self._nomeUsuario}"

admin1 = Admin("Baltazar")

admin1.digaOla()