# -*- coding: utf-8 -*-
"""Parte I - Introdução a POO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SrxLA008TKTRpJmYZXrL0pGd6GAB5zxX
"""

# 1-A)
# 2-A)
# 3-A)
# 4-C)

# 5- Usuario
#    nomeP - nomeS
#    Hello

#######################################################
class Usuario():
    nomeP = "Default"
    nomeS = "Default"

    def hello(self):
        return (f"Olá {self.nomeP} {self.nomeS}")


#######################################################
usuario1 = Usuario()

usuario1.nomeP = input("Nome ").capitalize()
print(f"{usuario1.nomeP}")
print("\n")
usuario1.nomeS = input("Sobrenome ").capitalize()
print(f"{usuario1.nomeS}")
print("\n")

print(usuario1.hello())
print("\n")

#######################################################
usuario2 = Usuario()

usuario2.nomeP = "Jane"
usuario2.nomeS = "Silva"

print(usuario2.hello())