# -*- coding: utf-8 -*-
"""Parte I - Introdução a POO - Uso do self e Métodos Mágicos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSfCeus_gUu2uYq4zEdCJPfYA6DkhvJH
"""

class Usuario():

  def __init__(self, primeiroNome, segundoNome):
    self.nomeP = primeiroNome
    self.nomeS = segundoNome

  def getNomeCompleto(self):
    return f"{self.nomeP} {self.nomeS}"
  def hello(self):
    return f"Olá {self.nomeP} {self.nomeS}"


usuario1 = Usuario("Johnny","Bravo")

print(usuario1.getNomeCompleto())
print(usuario1.hello())