# -*- coding: utf-8 -*-
"""Desafios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKFyCREQ6H0-rmh4bUaMaBJ-fBh6ux7c

# **ALG_EXTRA_01**

**1-** Fazer um algoritmo para ler o valor do lado de um quadrado e mostrar a área (lado**2) e seu perímetro
"""

l = int(input("Lados do quadrado "))

print("Área =" ,l**2)
print("Perímetro =" ,l*4)

"""**2-** Elaborar um algoritmo para ler o nome e a quantidade de filhos de uma pessoa.
Mostrar a mensagem: “Fulano tem 5 filhos.”
"""

N = (input("Nome "))
No = (input("Número de filhos "))

print(N,No,sep=" tem ",end=" filhos ")

"""**3-** Fazer um algoritmo para ler os valores da base e altura de um retângulo e mostrar seu perímetro ( 2 x ( base + altura ) ) e sua área ( base x altura)."""

Ba = float(input("Base "))
Al = float(input("Altura "))

print("Perímetro" ,2*(Ba+Al))
print("Área" ,Ba*Al)

"""**4-** Fazer um algoritmo para ler o valor do lado de um cubo e
mostrar sua área ( 6 x lado2) e seu volume ( lado3).
"""

Lado = float(input("Lado "))

print("Área" ,6*Lado)
print("Volume" ,Lado**2)

"""**5-** Elaborar um algoritmo para ler dois números e mostrar o quociente e o resto da
divisão inteira do primeiro pelo segundo número.
"""

n1 = int(input("Número 1 = "))
n2 = int(input("Número 2 = "))

print("Resultado" ,n1/n2)
print("Resto" ,n1%n2)

"""**6-** Criar um algoritmo para ler a base e a altura de um triângulo e
mostrar a sua área ( ( base x altura ) / 2 ).
"""

Ba = float(input("Base "))
Al = float(input("Altura "))

print("Área" ,(Ba*Al)/2)

"""**7-** Construir um algoritmo para ler o raio de uma circunferência e
mostrar o perímetro ( 2 x π x raio ) e a área ( π x raio2). Utilize o π como constante.
"""

import math

Raio = float(input("Raio "))

print("Perímetro" ,2*math.pi*Raio)
print("Área" ,math.pi*Raio**2)

"""# **EstruturaSequencial - PythonBrasil**

**1-** Faça um Programa que mostre a mensagem "Alo mundo" na tela.
"""

print("Ola mundo")

"""**2-** Faça um Programa que peça um número e então mostre a mensagem O número informado foi [número]."""

n1 = input("Número ")

print("O número informado foi", n1)

"""**4-** Faça um Programa que peça as 4 notas bimestrais e mostre a média."""

n1 = int(input("Primeira nota "))
n2 = int(input("Segunda nota "))
n3 = int(input("Terceira nota "))
n4 = int(input("Quarta nota "))

print("Média",(n1+n2+n3+n4)/4)

"""**7-** Faça um Programa que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário."""

L = int(input("Lado do quadrado "))

print("Dobro da área",(L**2)*2)

"""**8-** Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês.
Calcule e mostre o total do seu salário no referido mês.
"""

Sh = float(input("Ganhos por hora "))
Mh = int(input("Cargo horário mês "))

print("Sálario por mês R$",Sh*Mh)

"""**11-** Faça um Programa que peça 2 números inteiros e um número real. Calcule e mostre:
**a.** o produto do dobro do primeiro com metade do segundo .
**b.** a soma do triplo do primeiro com o terceiro.
**c.** o terceiro elevado ao cubo.
"""

n1 = int(input("Primeiro número "))
n2 = float(input("Número real "))
n3 = ((n1*2)*(n2/2))

print("Produto",n3)
print("Soma",(n1*3)+n3)
print("Resultado",n3**3)

"""**12-** Tendo como dados de entrada a altura de uma pessoa, construa um algoritmo que calcule seu peso ideal,
usando a seguinte fórmula: (72.7*altura) - 58
"""

h = float(input("Áltura em metros "))

print("Peso ideal",72.7*h - 58)

h = float(input("Áltura em metros "))

Pf = float(62.1*h - 44.7)
Pm = float(72.7*h - 58)

"""**14-** João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de
seu trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento de pesca do
estado de São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente. João precisa que você
faça um programa que leia a variável peso (peso de peixes) e verifique se há excesso. Se houver, gravar na
variável excesso e na variável multa o valor da multa que João deverá pagar. Caso contrário mostrar tais
variáveis com o conteúdo ZERO.
"""

p = float(input("Peso total em Kg "))

if p > 50:
  E = (p-50)
  print("Excesso Kg",E)
else:
  E = 0

print("Multa R$",E*4.00)

"""**15-** Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês.
Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11% para o Imposto
de Renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê:
**a.** salário bruto.
**b.** quanto pagou ao INSS.
**c.** quanto pagou ao sindicato.
**d.** o salário líquido.
calcule os descontos e o salário líquido.
"""

Sh = float(input("Ganhos por hora "))
Mh = int(input("Cargo horário mês "))
Sb = (Sh*Mh)
IN = (Sb*0.08)
Si = (Sb*0.05)

print("Sálario bruto R$",Sb)
print("INSS R$",IN)
print("Sindicato R$",Si)
print("Sálario liquido R$",Sb-(Sb*0.11)-IN-Si)

"""**16-** Faça um programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área
a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 3 metros quadrados e que a tinta é
vendida em latas de 18 litros, que custam R$ 80,00. Informe ao usuário a quantidades de latas de tinta a serem
compradas e o preço total.
"""

import math
Mq = float(input("Metros quadrados da área "))
L = int(math.ceil((Mq/3)/18))

print("Latas necessarias",L)
print("Preço total R$",L*80)

"""**17-** Faça um Programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área
a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 6 metros quadrados e que a tinta é
vendida em latas de 18 litros, que custam Rs 80,00 ou em galões de 3,6 litros, que custam R$ 25,00.
Informe ao usuário as quantidades de tinta a serem compradas e os respectivos preços em 3 situações:

*   comprar apenas latas de 18 litros;
*   comprar apenas galões de 3,6 litros;
*   misturar latas e galões, de forma que o preço seja o menor. Acrescente 10% de folga e sempre
arredonde os valores para cima, isto é, considere latas cheias.
"""

import math
Mq = float(input("Metros quadrados da área "))
L = int(math.ceil((Mq/6)/18)*1.10)
G = int(math.ceil((Mq/6)/3.6)*1.10)
Mix_latas = math.floor(((Mq/6)/18)*1.10)
Sobra_latas = ((Mq/6)%18)
Mix_galoes = math.ceil((Sobra_latas/3.6)*1.10)

print("Preço latas R$",L*80)
print("Preço Galões R$",G*25)

print("Latas",Mix_latas,"Galões", Mix_galoes)
print("Preço total", (Mix_latas*80) + (Mix_galoes*25))

"""**18-** Faça um programa que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link de
Internet (em Mbps), calcule e informe o tempo aproximado de download do arquivo usando este link (em
minutos).
"""

Tamanho_Arquivo = int(input("Tamanho do arquivo mb "))
Velocidade_link = int(input("Velocidade do link "))

print("Tempo de download em minutos", (Tamanho_Arquivo/Velocidade_link)/60)

"""# **Lista_Introducao_PRG1_TRE**

**9-** Faça um algoritmo que calcule o volume de uma lata de óleo. Escreva o resultado.
"""

import math

Raio = float(input("Raio "))
Altura = float(input("Altura "))

print("Volume =", math.pi * Raio** 2 * Altura)

"""**10-** Faça um algoritmo que leia as 3 notas de um aluno e calcule e escreva a média final
deste aluno. Considerar que a média é ponderada e que o peso das notas é: 2,3 e 5,
respectivamente.
"""

Media1 = float(input("Média 1 "))
Media2 = float(input("Média 2 "))
Media3 = float(input("Média 3 "))

print("Média",Media1*0.23+Media2*0.5+Media3*0.27)

"""**11-** Faça um algoritmo que leia as coordenadas de dois pontos, P1 (x1, y1) e P2 (x2, y2)
respectivamente, e calcule e escreva a distância entre eles.
"""

import math

x1 = int(input("X1 "))
y1 = int(input("Y1 "))
x2 = int(input("X2 "))
y2 = int(input("Y2 "))

print("Distância",math.sqrt((x2-x1)**2+(y2-y1)**2))

"""**12-** Um sistema de equações lineares da forma:

pode ser resolvido utilizando-se as seguintes fórmulas:
"""

a = float(input("a "))
b = float(input("b "))
c = float(input("c "))
d = float(input("d "))
e = float(input("e "))
f = float(input("f "))

print("X =",(c*e)-(b*f)/(a*e)-(b*d))
print("Y =",(a*f)-(c*d)/(a*e)-(b*d))

"""**13-** O custo ao consumidor de um carro novo é a soma do custo de fábrica com a
percentagem do distribuidor e dos impostos (aplicados ao custo de fábrica).
Supondo que a percentagem do distribuidor seja de 28% e os impostos de 45%,
escrever um algoritmo que leia o custo de fábrica de um carro e escreva o custo ao
consumidor.
"""

Custo_fabrica = int(input("Custo de fábrica "))

print("Custo do consumidor", Custo_fabrica*0.28+Custo_fabrica*0.45+Custo_fabrica)

"""**14-** Faça um algoritmo que leia a idade de uma pessoa expressa em dias e mostre-a
expressa em anos, meses e dias.
"""

import math

Idade_dias = int(input("Idade da pessoa em dias "))
Idade_anos = Idade_dias/365
Idade_mes = Idade_dias/30.417
Anos = math.floor(Idade_anos)
Mes = math.floor((Idade_dias%365)/30.417)
Dias = math.floor((Idade_dias%365)%30.417)

print("Anos",Anos,"Meses",Mes,"Dias",Dias)
print("Anos",Idade_anos)
print("Meses",Idade_mes)
print("dias",Idade_dias)

"""**15-** Faça um algoritmo que leia o tempo de duração de um evento em uma fábrica
expressa em segundos e mostre-o expresso em horas, minutos e segundos.
"""

import math

Tempo_evento_segundos = int(input("Duração do evento em segundos "))

print("Horas",math.floor(Tempo_evento_segundos/3600),"Minutos",math.floor((Tempo_evento_segundos%3600)/60),"Segundos",math.floor((Tempo_evento_segundos%3600)%60))

"""**16-** O governador acaba de liberar R$ 1.000.000.000,00 para construção de casas
populares. Cada casa custa o equivalente a 90 salários mínimos. Faça um algoritmo
que leia o valor do salário mínimo e calcule a quantidade de casas que podem ser
construídas com o recurso liberado.
"""

import math
Salario_minimo = float(input("Salário mínimo "))

print("Casas",math.floor(1000000000.00/(90*Salario_minimo)))