# -*- coding: utf-8 -*-
"""Funções

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h126RxP2KhU5y1Y_TcoiesBE5foSLy0A

**1. Faça uma função para converter uma temperatura em graus Fahrenheit para
Celsius. A temperatura em Fahrenheit é o dado de entrada e a temperatura em
Celsius é o dado de saída. Utilize a fórmula C = (F - 32) * 5/9, onde F é a
temperatura em Fahrenheit e C é a temperatura em Celsius.**
"""

def Fahr_Celsius(Fahrenheit):
  Celsius = (Fahrenheit - 32) * 5/9
  return Celsius

C = Fahr_Celsius(int(input("Temperatura em Fahrenheit ")))
print(f"{C}")

"""**2. Faça uma função que calcule a hipotenusa. Os catetos são os dados de entrada e
a hipotenusa é o dado de saída.**

**(hipotenusa = _/catetoA^2 + catetoB^2)**
"""

import math

def Hipot(CatetoA, CatetoB):
  Hipotenusa = math.sqrt(CatetoA**2 + CatetoB**2)
  return Hipotenusa

H = Hipot(int(input("Cateto A ")), int(input("Cateto B ")))
print(f"{H}")

"""**3. Escreva um programa para ler as notas das duas avaliações de um aluno no
semestre. Faça uma função que receba as duas notas por parâmetro e calcule e
escreva a média semestral e a mensagem “PARABÉNS! Você foi aprovado!”
somente se o aluno foi aprovado (considere 6.0 a média mínima para aprovação).**
"""

def Result(Nota1, Nota2):
  Media = (Nota1 + Nota2)/2
  return Media

resultado = Result(int(input("Nota 1 ")), int(input("Nota 2 ")))
if resultado >= 6:
  print(f"{resultado}")
  print(f"Aprovado")

"""**4. Faça um programa que leia a altura e o sexo (codificado da seguinte forma:
1-feminino 2-masculino) de uma pessoa. Depois faça uma função chamada
pesoideal que receba a altura e o sexo via parâmetro e que calcule e retorne seu
peso ideal, utilizando as seguintes fórmulas:**

**• para homens: (72.7 * h) – 58**

**• para mulheres: (62.1 * h) – 44.7**

**Observação: Altura = h (na fórmula acima).**
"""

def Peso_ideal(Genero, Altura):
  if Genero == 1:
    Peso = (62.1 * Altura) - 44.7
  elif Genero == 2:
    Peso = (72.7 * Altura) - 58
  return Peso

pesofinal = Peso_ideal(int(input("Genero ")), float(input("Altura em metros ")))
print(f"O seu Peso ideal é {pesofinal}")

"""**5. Escreva um programa para ler o número de lados de um polígono regular e a
medida do lado (em cm). Faça uma função que receba como parâmetro o número
de lados e a medida do lado deste polígono e calcule e imprima o seguinte:**

**• Se o número de lados for igual a 3, escrever TRIÂNGULO e o valor do seu
perímetro.**

**• Se o número de lados for igual a 4, escrever QUADRADO e o valor da sua área.**

**• Se o número de lados for igual a 5, escrever PENTÁGONO.**

**Observação: Considere que o usuário só informará os valores 3, 4 ou 5.**
"""

def Identif(Lados, Med_Lado):
  if Lados == 3:
    P_Triang = Med_Lado * 3
    print(f"Triângulo")
    print(f"{P_Triang}")
  elif Lados == 4:
    A_Quadr = Med_Lado ** 2
    print(f"Quadrado")
    print(f"{A_Quadr}")
  elif Lados == 5:
    print(f"Pentágono")

Identif(int(input("Quantidade de lados ")), int(input("Medida do lado ")))

"""**6. Escreva uma função que recebe 2 números inteiros n1 e n2 como entrada e
retorna a soma de todos os números inteiros contidos no intervalo n1,n2. Use
esta função em um programa que lê n1 e n2 do usuário e imprime a soma.**
"""

def Soma_inter(Num1, Num2):
  Num_inter = list(range(Num1,Num2+1))
  print(Num_inter)
  print("")
  Result = sum(Num_inter)
  return Result

Resultado = Soma_inter(int(input("Numero 1 ")), int(input("Numero 2 ")))
print(f"{Resultado}")

"""**7. Escreva uma função que receba um número inteiro e imprima o mês
correspondente ao número. Por exemplo, 2 corresponde a “fevereiro”. O
procedimento deve mostrar uma mensagem de erro caso o número recebido não
faça sentido. Gere também um programa que leia um valor e chame a função
criada.**
"""

box_mes = []

def Num_mes():
  while True:
      try:
          Num = int(input("Mês "))
          print("")
          if Num > 12 or Num < 1:
              raise ValueError
          break
      except ValueError:
          print("Numero invalido.")
          print("")
  box_mes.append(Num)
  nummes = {1:"Janeiro", 2:"Fevereiro", 3:"Março", 4:"Abril", 5:"Maio", 6:"Junho", 7:"Julho", 8:"Agosto", 9:"Setembro", 10:"Outubro", 11:"Novembro", 12:"Dezembro"}
  trocar_n = nummes.get
  Final = [trocar_n(n, n) for n in box_mes]
  return Final

Result = Num_mes()
print(f"{Result[0]}")

"""**8. Escreva uma função que receba um número natural e imprima os três primeiros
caracteres do dia da semana correspondente ao número. Por exemplo, 7
corresponde a “SAB”. O procedimento deve mostrar uma mensagem de erro caso
o número recebido não corresponda a um dia da semana. Gere também um
programa que utilize essa função, chamando-a, mas antes lendo um valor para
passagem de parâmetro.**
"""

box_sem = []

def Num_sem():
  while True:
      try:
          Num = int(input("Semana "))
          print("")
          if Num > 7 or Num < 1:
              raise ValueError
          break
      except ValueError:
          print("Numero invalido.")
          print("")
  box_sem.append(Num)
  numsem = {1:"Dom", 2:"Seg", 3:"Ter", 4:"Qua", 5:"Qui", 6:"Sex", 7:"Sab"}
  trocar_n = numsem.get
  Final = [trocar_n(n, n) for n in box_sem]
  return Final

Result = Num_sem()
print(f"{Result[0]}")

"""**9. Escreva uma função que receba dois números inteiros x e y. Essa função deve
verificar se x é divisível por y. No caso positivo, a função deve retornar 1, caso
contrário zero. Escreva também um programa para testar tal função.**
"""

def Div(X, Y):
  if (X % Y) == 0:
    result = 1
  else:
    result = 0
  return result

R = Div(int(input("X ")), int(input("Y ")))
print(f"{R}")

"""**10. Criar uma função que calcule e retorne o MAIOR entre dois valores recebidos como
parâmetros. Um programa para testar tal função deve ser criado.**
"""

def Maior_menor(X, Y):
  if X > Y:
    Result = X
  else:
    Result = Y
  return Result

R = Maior_menor(int(input("X ")), int(input("Y ")))
print(f"{R}")

"""**11. Crie uma função que realize a conversão de Polegadas (pol) para Centímetros
(cm), onde pol é passado como parâmetro e cm é retornado. Sabe-se que 1
polegada tem 2.54 centímetros. Crie também um programa para testar tal função.**
"""

def Pol_Cen(Polegadas):
  Result = Polegadas * 2.54
  return Result

conv = Pol_Cen(int(input("Polegadas ")))
print(conv)