# -*- coding: utf-8 -*-
"""Atividade Prática 03  Design Patterns (Padrões de Projeto) - Decorator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sf6dV11T82An-f4D4F46IOCmFVAup545
"""

from abc import ABC, abstractmethod

class Drinks(ABC):

  def __init__(self, descricao, preco):
    self.descricao = descricao
    self.preco = preco

  def getDescricao(self):
    return self.descricao

  def getPreco(self):
    return self.preco

class Caipira(Drinks):
  def __init__(self):
    super().__init__("Caipira", 10)

class Cachaca(Drinks):
  def __init__(self):
    super().__init__("Cachaça", 10)

class AddAditivos(Drinks, ABC):
  def __init__(self, descricao, preco, drink):
    super().__init__(descricao, preco)
    self.drink = drink

  @abstractmethod
  def getDescricao(self):
    pass

  @abstractmethod
  def getPreco(self):
    pass

class Saque(AddAditivos):
  def __init__(self, drink):
    super().__init__("Saquê", 2, drink)

  def getDescricao(self):
    return self.drink.getDescricao() + ", " + self.descricao

  def getPreco(self):
    return self.drink.getPreco() + self.preco

class Abacaxi(AddAditivos):
  def __init__(self, drink):
    super().__init__("Abacaxi", 2, drink)

  def getDescricao(self):
    return self.drink.getDescricao() + ", " + self.descricao

  def getPreco(self):
    return self.drink.getPreco() + self.preco

class Kiwi(AddAditivos):
  def __init__(self, drink):
    super().__init__("Kiwi", 2, drink)

  def getDescricao(self):
    return self.drink.getDescricao() + ", " + self.descricao

  def getPreco(self):
    return self.drink.getPreco() + self.preco

class Morango(AddAditivos):
  def __init__(self, drink):
    super().__init__("Morango", 2, drink)

  def getDescricao(self):
    return self.drink.getDescricao() + ", " + self.descricao

  def getPreco(self):
    return self.drink.getPreco() + self.preco

class Limao(AddAditivos):
  def __init__(self, drink):
    super().__init__("Limão", 2, drink)

  def getDescricao(self):
    return self.drink.getDescricao() + ", " + self.descricao

  def getPreco(self):
    return self.drink.getPreco() + self.preco

class Acucar(AddAditivos):
  def __init__(self, drink):
    super().__init__("Açúcar", 2, drink)

  def getDescricao(self):
    return self.drink.getDescricao() + ", " + self.descricao

  def getPreco(self):
    return self.drink.getPreco() + self.preco

class Adocante(AddAditivos):
  def __init__(self, drink):
    super().__init__("Adoçante", 2, drink)

  def getDescricao(self):
    return self.drink.getDescricao() + ", " + self.descricao

  def getPreco(self):
    return self.drink.getPreco() + self.preco

class Gelo(AddAditivos):
  def __init__(self, drink):
    super().__init__("Gelo", 2, drink)

  def getDescricao(self):
    return self.drink.getDescricao() + ", " + self.descricao

  def getPreco(self):
    return self.drink.getPreco() + self.preco

class Vodka(AddAditivos):
  def __init__(self, drink):
    super().__init__("Vodka", 2, drink)

  def getDescricao(self):
    return self.drink.getDescricao() + ", " + self.descricao

  def getPreco(self):
    return self.drink.getPreco() + self.preco



class Cardapio():
  def Bebida(self, ID):
    if ID == 1:
      bebida = Cachaca()
      bebida = Limao(bebida)
      bebida = Gelo(bebida)
      bebida = Acucar(bebida)
      return bebida
    else:
      return None


bebida1 = Caipira()
bebida1 = Saque(bebida1)
bebida1 = Abacaxi(bebida1)
bebida1 = Kiwi(bebida1)
bebida1 = Acucar(bebida1)

print(f"Ingredientes = {bebida1.getDescricao()}")
print(f"Custo = {bebida1.getPreco():.2f}")
print("")
print("--------------------------------------------------------------------------------------------------")

bebida2 = Caipira()
bebida2 = Vodka(bebida2)
bebida2 = Morango(bebida2)
bebida2 = Acucar(bebida2)

print(f"Ingredientes = {bebida2.getDescricao()}")
print(f"Custo = {bebida2.getPreco():.2f}")
print("")
print("--------------------------------------------------------------------------------------------------")

Cardapio = Cardapio()
caipirinha = Cardapio.Bebida(1)

print(f"Ingredientes = {caipirinha.getDescricao()}")
print(f"Custo = {caipirinha.getPreco():.2f}")